
# Define some colors
BLACK = (  0,   0,   0)
WHITE = (255, 255, 255)
RED   = (255,   0,   0)
BLUE = (0, 0, 255)
YELLOW = (255, 255, 0)
PINK = (255, 0, 255)

# Set the height and width of the screen
SCREEN_WIDTH = 1024
SCREEN_HEIGHT = 768

#LEVEL States

LEVEL_STATE_NEW           = 1
LEVEL_STATE_READY         = 2
LEVEL_STATE_SUSPENDED     = 3
LEVEL_STATE_RUNNING       = 4
LEVEL_STATE_IN_TRANSITION = 5
LEVEL_STATE_DEFUNCT       = 6


MUSIC_LEVEL = '1'
MUSIC_MENU = '2'
MUSIC_PAUSED = '3'
MUSIC_CREDITS = '4'
MUSIC_HELP = '5'

CHANNEL_BACKGROUND = 1
CHANNEL_MUSIC = 3
CHANNEL_ACTION = 2

P_STATE_NORMAL   = '1'
P_STATE_SHOOTING = '2'
P_STATE_DAMAGE = '3'
P_STATE_NORMAL_90   = '4'
P_STATE_NORMAL_50   = '5'
P_STATE_NORMAL_30   = '6'

